# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
# SPDX-FileCopyrightText: 2023 MASH project contributors
# SPDX-FileCopyrightText: 2026 Timofej Luitle
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Perform Forgejo installation tasks
  when: forgejo_enabled | bool
  tags:
    - setup-all
    - setup-forgejo
    - install-all
    - install-forgejo
  block:
    - name: Validate Forgejo configuration
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"
    - name: Install Forgejo
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/install.yml"

- name: Perform Forgejo uninstallation tasks
  when: not forgejo_enabled | bool
  tags:
    - setup-all
    - setup-forgejo
  block:
    - name: Uninstall Forgejo
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/uninstall.yml"

- name: Perform Forgejo OAuth2 configuration tasks
  when: forgejo_enabled | bool
  tags:
    - configure-oauth-forgejo
  block:
    - name: Configure OAuth2 provider for Forgejo
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/configure_oauth.yml"
